/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bda.itson.Presentacion;

import dtos.PersonaDTO;
import interfaces.IConsultas;
import java.time.LocalDate;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import negocio.Consultas;
import tablas.Conversiones;

/**
 *
 * @author abelc
 */
public class Historial extends javax.swing.JFrame {

    PersonaDTO personaDTO;
    IConsultas consultas;
    Conversiones tabla;

    /**
     * Creates new form Historial
     */
    public Historial(PersonaDTO persona) {
        this.personaDTO = persona;
        this.consultas = new Consultas();
        this.tabla = new Conversiones();
        initComponents();
        jLabel2.setText("Historial de " + persona.getNombres() + " " + persona.getApellidoPaterno() + " " + persona.getApellidoMaterno());
        crearTablaHistorial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        tramiteComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JButton();
        generarReporteBtn = new javax.swing.JButton();
        regresarBtn1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historialTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));

        jPanel3.setBackground(new java.awt.Color(107, 27, 56));
        jPanel3.setPreferredSize(new java.awt.Dimension(482, 55));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descarga (1).png"))); // NOI18N

        jLabel2.setText("Historial de trámites de");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 508, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel2)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        datePicker2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        datePicker2.setName(""); // NOI18N

        tramiteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Licencias", "Placas" }));
        tramiteComboBox.setBackground(new java.awt.Color(255, 255, 255));
        tramiteComboBox.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setText("Desde:");
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setText("Hasta:");
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));

        buscarBtn.setText("Buscar");
        buscarBtn.setBackground(new java.awt.Color(107, 27, 56));
        buscarBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        generarReporteBtn.setText("Generar reporte");
        generarReporteBtn.setBackground(new java.awt.Color(107, 27, 56));
        generarReporteBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        generarReporteBtn.setForeground(new java.awt.Color(255, 255, 255));
        generarReporteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReporteBtnActionPerformed(evt);
            }
        });

        regresarBtn1.setText("Regresar");
        regresarBtn1.setBackground(new java.awt.Color(107, 27, 56));
        regresarBtn1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        regresarBtn1.setForeground(new java.awt.Color(255, 255, 255));
        regresarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtn1ActionPerformed(evt);
            }
        });

        historialTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        historialTabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        historialTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        historialTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(historialTabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tramiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regresarBtn1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(datePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(generarReporteBtn)
                                .addGap(29, 29, 29))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 73, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buscarBtn)
                                .addGap(267, 267, 267))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tramiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(buscarBtn)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regresarBtn1)
                            .addComponent(generarReporteBtn))
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void generarReporteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReporteBtnActionPerformed

    }//GEN-LAST:event_generarReporteBtnActionPerformed

    private void regresarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtn1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarBtn1ActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        LocalDate fecha1 = datePicker1.getDate(); // Obtener la fecha del primer datePicker
        LocalDate fecha2 = datePicker2.getDate();
        if (tramiteComboBox.getSelectedItem() == "Todos") {
            crearTablaHistorial();
        }
        if (tramiteComboBox.getSelectedItem() == "Licencias") {
            DefaultTableModel model = (DefaultTableModel) historialTabla.getModel();
            model.setRowCount(0);
            DefaultTableModel newModel = tabla.licenciasTableModel(consultas.obtenerLicenciasPorPersona(personaDTO));
            historialTabla.setModel(newModel);
        }
        if (tramiteComboBox.getSelectedItem() == "Placas") {
            DefaultTableModel model = (DefaultTableModel) historialTabla.getModel();
            model.setRowCount(0);
            DefaultTableModel newModel = tabla.placasTableModel(consultas.obtenerPlacasPorPersona(personaDTO));
            historialTabla.setModel(newModel);
        }
        if (tramiteComboBox.getSelectedItem() == "Todos" && fecha1 != null && fecha2 != null) {
            Calendar desde = Calendar.getInstance();
            desde.clear();
            desde.set(fecha1.getYear(), fecha1.getMonthValue() - 1, fecha1.getDayOfMonth());
            Calendar hasta = Calendar.getInstance();
            hasta.clear();
            hasta.set(fecha2.getYear(), fecha2.getMonthValue() - 1, fecha2.getDayOfMonth());
            DefaultTableModel model = (DefaultTableModel) historialTabla.getModel();
            model.setRowCount(0);
            DefaultTableModel newModel = tabla.tramitesTableModel(consultas.obtenerLicenciasPorPeriodo(personaDTO, desde, hasta), consultas.obtenerPlacasPorPeriodo(personaDTO, desde, hasta));
            historialTabla.setModel(newModel);
        }
        if (tramiteComboBox.getSelectedItem() == "Licencia" && fecha1 != null && fecha2 != null) {
            Calendar desde = Calendar.getInstance();
            desde.clear();
            desde.set(fecha1.getYear(), fecha1.getMonthValue() - 1, fecha1.getDayOfMonth());
            Calendar hasta = Calendar.getInstance();
            hasta.clear();
            hasta.set(fecha2.getYear(), fecha2.getMonthValue() - 1, fecha2.getDayOfMonth());
            DefaultTableModel model = (DefaultTableModel) historialTabla.getModel();
            model.setRowCount(0);
            DefaultTableModel newModel = tabla.licenciasTableModel(consultas.obtenerLicenciasPorPeriodo(personaDTO, desde, hasta));
            historialTabla.setModel(newModel);
        }
           if (tramiteComboBox.getSelectedItem() == "Placas" && fecha1 != null && fecha2 != null) {
            Calendar desde = Calendar.getInstance();
            desde.clear();
            desde.set(fecha1.getYear(), fecha1.getMonthValue() - 1, fecha1.getDayOfMonth());
            Calendar hasta = Calendar.getInstance();
            hasta.clear();
            hasta.set(fecha2.getYear(), fecha2.getMonthValue() - 1, fecha2.getDayOfMonth());
            DefaultTableModel model = (DefaultTableModel) historialTabla.getModel();
            model.setRowCount(0);
            DefaultTableModel newModel = tabla.placasTableModel(consultas.obtenerPlacasPorPeriodo(personaDTO, desde, hasta));
            historialTabla.setModel(newModel);
        }

    }//GEN-LAST:event_buscarBtnActionPerformed
    private void crearTablaHistorial() {
        DefaultTableModel model = (DefaultTableModel) historialTabla.getModel();
        model.setRowCount(0);
        DefaultTableModel newModel = tabla.tramitesTableModel(consultas.obtenerLicenciasPorPersona(personaDTO), consultas.obtenerPlacasPorPersona(personaDTO));
        historialTabla.setModel(newModel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PersonaDTO persona = new PersonaDTO();
                Historial historial = new Historial(persona);
                historial.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JButton generarReporteBtn;
    private javax.swing.JTable historialTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresarBtn1;
    private javax.swing.JComboBox<String> tramiteComboBox;
    // End of variables declaration//GEN-END:variables
}
