/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bda.itson.Presentacion;

/**
 *
 * @author fabri
 */
public class RegistrarLicencia extends javax.swing.JPanel {

    int costo;

    /**
     * Creates new form RegistrarLicencia
     */
    public RegistrarLicencia() {
        initComponents();
        costo = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxVigencia = new javax.swing.JComboBox<>();
        txtCostoReal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMostrarCosto = new javax.swing.JLabel();

        boxVigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 año", "2 años", "3 años" }));
        boxVigencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxVigenciaItemStateChanged(evt);
            }
        });

        txtCostoReal.setText("Costo: ");

        jLabel2.setText("Vigencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtCostoReal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boxVigencia, 0, 146, Short.MAX_VALUE)
                    .addComponent(txtMostrarCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(boxVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCostoReal)
                    .addComponent(txtMostrarCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boxVigenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxVigenciaItemStateChanged

        if (boxVigencia.getSelectedItem() == "1 año") {
            costo = 600;
            txtMostrarCosto.setText(String.valueOf(costo));
        }

        if (boxVigencia.getSelectedItem() == "2 años") {
            costo=900;
            txtMostrarCosto.setText(String.valueOf(costo));
        }

        if (boxVigencia.getSelectedItem() == "3 años") {
            costo = 1100;
            txtMostrarCosto.setText(String.valueOf(costo));
        }


    }//GEN-LAST:event_boxVigenciaItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxVigencia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtCostoReal;
    private javax.swing.JLabel txtMostrarCosto;
    // End of variables declaration//GEN-END:variables
}
