/**
 * Clase creada el 11 de Abril de 2024
 *
 */
package bda.itson.Presentacion;

import dtos.PersonaDTO;
import dtos.PlacaDTO;
import dtos.VehiculoDTO;
import interfaces.IRegistrarPlaca;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Consultas;
import negocio.RegistrarPlaca;
import tablas.Conversiones;

/**
 *
 * Interfaz grafica de usuario para mostrar los vehiculos del cliente
 *
 * @author abelc
 */
public class Vehiculos extends javax.swing.JFrame {

    PersonaDTO personaDTO;
    IRegistrarPlaca placa;
    Conversiones tabla;
    PlacaDTO placaDTO;
    Consultas consultas;

    /**
     * Creates new form Vehiculos
     *
     * @param persona
     */
    public Vehiculos(PersonaDTO persona) {
        consultas = new Consultas();
        this.personaDTO = persona;
        tabla = new Conversiones();
        this.placaDTO = new PlacaDTO();
        this.placa = new RegistrarPlaca();
        initComponents();
        DefaultTableModel model = (DefaultTableModel) tablaVehiculos.getModel();
        model.setRowCount(0);
        List<VehiculoDTO> vehiculos = placa.obtenerVehiculosDePersona(persona);
        DefaultTableModel newModel = tabla.vehiculosTableModel(vehiculos);
        tablaVehiculos.setModel(newModel);
        tablaVehiculos.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        parametroTxtField = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        regresarBtn = new javax.swing.JButton();
        seleccionarBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));

        jPanel2.setBackground(new java.awt.Color(107, 27, 56));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descarga (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione un vehiculo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2))
        );

        parametroTxtField.setBackground(new java.awt.Color(255, 255, 255));
        parametroTxtField.setForeground(new java.awt.Color(0, 0, 0));

        buscarBtn.setBackground(new java.awt.Color(107, 27, 56));
        buscarBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        tablaVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        tablaVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaVehiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaVehiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablaVehiculos);

        regresarBtn.setBackground(new java.awt.Color(107, 27, 56));
        regresarBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        seleccionarBtn1.setBackground(new java.awt.Color(107, 27, 56));
        seleccionarBtn1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        seleccionarBtn1.setForeground(new java.awt.Color(255, 255, 255));
        seleccionarBtn1.setText("Tramitar placa");
        seleccionarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(parametroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarBtn)
                        .addGap(89, 89, 89))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(regresarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seleccionarBtn1)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parametroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionarBtn1)
                    .addComponent(regresarBtn))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para ejecutar la busqueda de un vehiculo mediante sus placas Se
     * pueden ingresar en formato AAA-111 o AAA111 El sistema verifica que
     * exista y que pertenezcan al mismo cliente
     *
     * @param evt
     */
    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        String codigo = parametroTxtField.getText().toUpperCase();
        if (!"".equals(codigo)) {
            if (!regex(codigo, "^[A-Za-z]{3}-?[1-9]{3}$")) {
                JOptionPane.showMessageDialog(null, "Introduce el codigo correcto, (ej AAA-111 o AAA111)");
                return;
            }
            if (!regex(codigo, "^[A-Za-z]{3}-[1-9]{3}$")) {
                codigo = formatearTexto(codigo);
                System.out.println(codigo);
            }
            List<PlacaDTO> placas = consultas.obtenerPlacasPorPersona(personaDTO);
            boolean existe = false;
            for (PlacaDTO pl : placas) {
                if (consultas.consultarPlacaPorCodigo(codigo).getCodigo() == null ? pl.getCodigo() == null : consultas.consultarPlacaPorCodigo(codigo).getCodigo().equals(pl.getCodigo())) {
                    existe = true;
                }
            }
            if (consultas.consultarPlacaPorCodigo(codigo) != null && existe == true) {
                DefaultTableModel model = (DefaultTableModel) tablaVehiculos.getModel();
                model.setRowCount(0);
                PlacaDTO placaUser = consultas.consultarPlacaPorCodigo(codigo);
                Object[] row = {placaUser.getCodigo(), placaUser.getEstado(), placaUser.getVehiculo().getColor(), placaUser.getVehiculo().getModelo(), placaUser.getVehiculo().getMarca(), placaUser.getVehiculo().getLinea(), placaUser.getVehiculo().getTipoVehiculo()};
                model.addRow(row);
                tablaVehiculos.setModel(model);
            } else {
                JOptionPane.showMessageDialog(null, "El codigo no esta asociado a ninguna placa del cliente");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Introduzca el codigo de la placa (ej. AAA-111)");

        }
    }//GEN-LAST:event_buscarBtnActionPerformed

    /**
     * Metodo privado para hacer verificaciones de expresiones regulares
     *
     * @param texto texto a verificar
     * @param expresionRegular expresion que se debe cumplir
     * @return verdadero si se cumple, falso en caso contrario
     */
    private boolean regex(String texto, String expresionRegular) {
        Pattern pattern = Pattern.compile(expresionRegular);
        Matcher matcher = pattern.matcher(texto);
        return matcher.matches();
    }

    /**
     * Metodo para regresar al menu principal
     *
     * @param evt
     */
    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        BuscarPersona buscarPersonas = new BuscarPersona(2);
        buscarPersonas.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_regresarBtnActionPerformed

    /**
     * Metodo para poner un guion entre los 3 digitos de letras y los 3 digitos
     * numericos Para que no existan problemas al buscar la placa en la base de
     * datos
     *
     * @param texto texto a cambiar
     * @return texto cambiado
     */
    public String formatearTexto(String texto) {
        String expresionRegular = "^([A-Za-z]{3})([1-9]{3})$";
        String textoFormateado = texto.replaceAll(expresionRegular, "$1-$2");
        return textoFormateado;
    }

    /**
     * Metodo para ejecutar la seleccion del vehiculo, y asi tramitar sus placas
     *
     * @param evt
     */
    private void seleccionarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarBtn1ActionPerformed
        obtenerDatosFilaSeleccionada();
        placa.generarPlaca(placaDTO);
        this.dispose();
        DlgConfirmaciones confirmacion = new DlgConfirmaciones(this, true, null, placaDTO, 2);

    }//GEN-LAST:event_seleccionarBtn1ActionPerformed

    /**
     * Metodo para obtener los datos del vehiculo seleccionado
     */
    public void obtenerDatosFilaSeleccionada() {
        int filaSeleccionada = tablaVehiculos.getSelectedRow();
        if (filaSeleccionada != -1) {
            String numSerie = tablaVehiculos.getValueAt(filaSeleccionada, 0).toString();
            VehiculoDTO vehiculo = placa.buscarVehiculoPorNumeroSerie(numSerie);
            placaDTO.setVehiculo(vehiculo);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un vehiculo.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField parametroTxtField;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JButton seleccionarBtn1;
    private javax.swing.JTable tablaVehiculos;
    // End of variables declaration//GEN-END:variables
}
